"use client";
import { useMemo, useState } from "react";

type Student={id:string;full_name_ar:string;student_no:string;class_name:string;grade_name:string};
type Rule={id:string;name_ar:string;default_points:number;min_points:number;max_points:number;is_mega:boolean;category_name:string|null};
export default function CheckIssuer({students,rules,pointValue}:{students:Student[];rules:Rule[];pointValue:number}){
 const [studentId,setStudentId]=useState(students[0]?.id||''); const [ruleId,setRuleId]=useState(rules[0]?.id||''); const rule=useMemo(()=>rules.find(r=>r.id===ruleId)||rules[0],[ruleId,rules]); const [points,setPoints]=useState(rule?.default_points||0); const [notes,setNotes]=useState(''); const [result,setResult]=useState<any>(null); const [loading,setLoading]=useState(false);
 function changeRule(id:string){setRuleId(id);const r=rules.find(x=>x.id===id);if(r)setPoints(r.default_points)}
 const student=students.find(s=>s.id===studentId);
 async function issue(){if(!studentId||!rule)return;setLoading(true);setResult(null);const r=await fetch('/api/checks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({studentId,ruleId:rule.id,points,reason:rule.name_ar,notes})});const j=await r.json();setResult(j);setLoading(false)}
 if(!students.length)return <section className="panel"><div className="empty-state"><b>لا يمكن إصدار شيك قبل إضافة الطلاب</b><span>أضف الصفوف والفصول ثم استورد الطلاب.</span></div></section>;
 return <section className="grid-2 checks-layout"><article className="panel"><div className="panel-head"><div><h3>إصدار شيك جديد</h3><p>القواعد والصلاحيات تُقرأ من قاعدة البيانات.</p></div></div><div className="form-grid"><label>الطالب<select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.full_name_ar} — {s.grade_name} / {s.class_name}</option>)}</select></label><label>سبب التميز<select value={ruleId} onChange={e=>changeRule(e.target.value)}>{rules.map(r=><option key={r.id} value={r.id}>{r.name_ar} — {r.default_points} نقاط</option>)}</select></label><label>عدد النقاط<input type="number" min={rule?.min_points||1} max={rule?.max_points||100} value={points} onChange={e=>setPoints(Number(e.target.value))}/></label><label>ملاحظات<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ملاحظة اختيارية"/></label></div><button className="btn primary full" disabled={loading||!studentId||!ruleId} onClick={issue}>{loading?'جارٍ الإصدار...':'إصدار الشيك وإضافة النقاط'}</button>{result&&<p className={`form-note ${result.ok?'ok-text':'error-text'}`}>{result.ok?`تم الإصدار: ${result.check.serial_no}`:result.error}</p>}</article><article className={`check-preview ${rule?.is_mega ? "gold" : ""}`}><div className="check-top"><span>شيك التميز الطلابي</span><b>{points} نقطة</b></div><h2>{rule?.name_ar||'شيك التميز'}</h2><p>يُمنح إلى</p><h3>{student?.full_name_ar||'اختر الطالب'}</h3><div className="check-value"><span>القيمة التقديرية</span><strong>{points*pointValue} ريال</strong></div><div className="check-bottom"><div><small>الحالة</small><b>{result?.ok?'تم الإصدار وتسجيله':'معاينة قبل الإصدار'}</b></div>{result?.ok&&<img src={`/api/qr?token=${encodeURIComponent(result.qrToken)}`} alt="QR"/>}</div><small className="serial">{result?.check?.serial_no||'EX-PREVIEW'}</small></article></section>
}
