import { useEffect, useMemo, useState } from "react";
import { niceError, rpc } from "./client";
import "./engagement.css";

type Student={id:string;student_no:string;name:string;grade_name:string;class_name:string;class_id?:string;points:number};
type Cycle={id:string;title_ar:string;description_ar:string;starts_at:string;ends_at:string;status:"SCHEDULED"|"ACTIVE"|"CLOSED";activated_at?:string|null;closed_at?:string|null};
type Nomination={class_id:string;student_ids:string[]};
type Leader={student_id:string;student_name:string;student_no:string;grade_name:string;class_name:string;nomination_count:number;rank:number};
type ParticipationClass={class_id:string;grade_name:string;class_name:string;nomination_count:number;complete:boolean};
type TeacherParticipation={staff_id:string;teacher_name:string;subject_name?:string|null;user_id?:string|null;account_ready:boolean;assigned_classes:number;started_classes:number;completed_classes:number;remaining_classes:number;nomination_count:number;classes:ParticipationClass[];status:"COMPLETE"|"PARTIAL"|"NOT_NOMINATED"|"NO_ACCOUNT"|"NO_CLASSES"};
type Data={is_teacher:boolean;can_activate:boolean;can_manage:boolean;visible_to_teacher:boolean;cycle:Cycle|null;cycles:Cycle[];assigned_class_ids:string[];my_nominations:Nomination[];leaderboard:Leader[];teacher_participation?:TeacherParticipation[]};
type Props={students:Student[]};
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString("ar-SA",{year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):"—";
const statusLabel=(s?:string)=>s==="ACTIVE"?"مفعلة":s==="SCHEDULED"?"بانتظار تفعيل الموجه":s==="CLOSED"?"منتهية":"غير مجدولة";
const participationLabel=(s:TeacherParticipation["status"])=>s==="COMPLETE"?"أكمل الترشيح":s==="PARTIAL"?"رشّح جزئيًا":s==="NOT_NOMINATED"?"لم يرشح":s==="NO_ACCOUNT"?"لا يوجد حساب مفعل":"لا توجد فصول مسندة";

export default function BehavioralExcellence({students}:Props){
  const[data,setData]=useState<Data|null>(null);const[selected,setSelected]=useState<Record<string,string[]>>({});const[busy,setBusy]=useState("");const[msg,setMsg]=useState("");const[reportFilter,setReportFilter]=useState<"ALL"|TeacherParticipation["status"]>("ALL");
  async function load(){try{const d=await rpc<Data>("api_behavioral_excellence");setData(d);const initial:Record<string,string[]>={};for(const n of d.my_nominations||[])initial[n.class_id]=(n.student_ids||[]).map(String);setSelected(initial)}catch(e){setMsg(niceError(e))}}
  useEffect(()=>{load()},[]);
  const classGroups=useMemo(()=>{if(!data)return[];const allowed=new Set((data.assigned_class_ids||[]).map(String));const map=new Map<string,{id:string;grade:string;name:string;students:Student[]}>();for(const s of students){if(!s.class_id||!allowed.has(String(s.class_id)))continue;const key=String(s.class_id);if(!map.has(key))map.set(key,{id:key,grade:s.grade_name,name:s.class_name,students:[]});map.get(key)!.students.push(s)}return [...map.values()].sort((a,b)=>`${a.grade}${a.name}`.localeCompare(`${b.grade}${b.name}`,"ar"))},[students,data]);
  const participation=data?.teacher_participation||[];
  const participationStats=useMemo(()=>({
    total:participation.length,
    complete:participation.filter(x=>x.status==="COMPLETE").length,
    partial:participation.filter(x=>x.status==="PARTIAL").length,
    missing:participation.filter(x=>x.status==="NOT_NOMINATED").length,
    noAccount:participation.filter(x=>x.status==="NO_ACCOUNT").length
  }),[participation]);
  const filteredParticipation=reportFilter==="ALL"?participation:participation.filter(x=>x.status===reportFilter);
  function toggle(classId:string,studentId:string){setMsg("");setSelected(v=>{const current=v[classId]||[];if(current.includes(studentId))return{...v,[classId]:current.filter(x=>x!==studentId)};if(current.length>=3){setMsg("لكل فصل 3 ترشيحات فقط. ألغِ اختيار طالب أولًا لتختار غيره.");return v}return{...v,[classId]:[...current,studentId]}})}
  async function saveClass(classId:string){const ids=selected[classId]||[];if(ids.length!==3){setMsg("اختر 3 طلاب بالضبط من هذا الفصل قبل الحفظ.");return}if(!data?.cycle)return;setBusy(classId);setMsg("");try{await rpc("api_behavioral_nominate",{p_cycle_id:data.cycle.id,p_class_id:classId,p_student_ids:ids});setMsg("تم حفظ ترشيحات التميز السلوكي لهذا الفصل.");await load()}catch(e){setMsg(niceError(e))}finally{setBusy("")}}
  async function cycleAction(action:"ACTIVATE"|"CLOSE"){if(!data?.cycle)return;setBusy(action);setMsg("");try{await rpc("api_behavioral_set_cycle_state",{p_cycle_id:data.cycle.id,p_action:action});setMsg(action==="ACTIVATE"?"تم تفعيل البرنامج. سيظهر للمعلمين داخل المدة المحددة، وأصبح تقرير متابعة الترشيحات متاحًا لك.":"تم إغلاق الدورة وإيقاف الترشيحات.");await load();window.dispatchEvent(new Event("behavioral-status-changed"))}catch(e){setMsg(niceError(e))}finally{setBusy("")}}
  function printParticipation(){
    if(!data?.cycle)return;
    const esc=(v:any)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]||m));
    const rows=participation.map((t,i)=>`<tr><td>${i+1}</td><td><b>${esc(t.teacher_name)}</b><small>${esc(t.subject_name||"")}</small></td><td>${esc(participationLabel(t.status))}</td><td>${t.assigned_classes}</td><td>${t.completed_classes}</td><td>${t.remaining_classes}</td><td>${t.nomination_count}</td></tr>`).join("");
    const w=window.open("","_blank","width=1100,height=800");if(!w)return;
    w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>تقرير متابعة ترشيحات التميز السلوكي</title><style>body{font-family:Arial,Tahoma,sans-serif;padding:24px;color:#1e2d36}h1{margin:0 0 5px;font-size:24px}p{margin:0 0 18px;color:#61737d}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.stats div{border:1px solid #ccd8dd;border-radius:10px;padding:10px}.stats b{display:block;font-size:22px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #cfd9dd;padding:8px;text-align:right}th{background:#eef4f5}td small{display:block;color:#667983;margin-top:2px}@media print{body{padding:0}}</style></head><body><h1>تقرير متابعة ترشيحات التميز السلوكي</h1><p>${esc(data.cycle.title_ar)} · ${esc(fmt(data.cycle.starts_at))} — ${esc(fmt(data.cycle.ends_at))}</p><div class="stats"><div>إجمالي المعلمين<b>${participationStats.total}</b></div><div>أكملوا الترشيح<b>${participationStats.complete}</b></div><div>ترشيح جزئي<b>${participationStats.partial}</b></div><div>لم يرشحوا<b>${participationStats.missing}</b></div></div><table><thead><tr><th>#</th><th>المعلم</th><th>الحالة</th><th>الفصول المسندة</th><th>المكتمل</th><th>المتبقي</th><th>عدد الترشيحات</th></tr></thead><tbody>${rows}</tbody></table></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250);
  }
  if(!data)return <><header className="topbar"><div><h1>التميز السلوكي</h1><p>جارٍ تحميل البرنامج...</p></div></header><main className="content"><div className="panel empty">جارٍ التحميل...</div></main></>;
  const c=data.cycle;
  return <><header className="topbar"><div><h1>التميز السلوكي</h1><p>برنامج دوري لترشيح الطلاب الأكثر تميزًا في السلوك</p></div>{c&&<span className={`behavioral-header-status ${c.status.toLowerCase()}`}>{statusLabel(c.status)}</span>}</header><main className="content behavioral-page">
    {c?<section className="panel behavioral-hero"><div><span className="eyebrow">برنامج دوري</span><h2>{c.title_ar}</h2><p>{c.description_ar}</p><div className="behavioral-dates"><span><small>البداية</small><b>{fmt(c.starts_at)}</b></span><span><small>النهاية</small><b>{fmt(c.ends_at)}</b></span></div></div><div className="behavioral-rule"><strong>3</strong><span>طلاب من كل فصل<br/>لكل معلم</span></div></section>:<section className="panel empty">لم يجهز مدير النظام دورة للتميز السلوكي حتى الآن.</section>}

    {c&&data.can_activate&&<section className="panel guidance-activation"><div><h3>تحكم الموجه الطلابي</h3><p>{c.status==="SCHEDULED"?"الدورة مجهزة ولكنها مخفية عن المعلمين. فعّلها عندما تريد بدء البرنامج.":c.status==="ACTIVE"?"الدورة مفعلة. يستطيع المعلمون الترشيح أثناء المدة المحددة، ويمكنك متابعة مشاركتهم من التقرير أدناه.":"هذه الدورة منتهية."}</p></div>{c.status==="SCHEDULED"?<button className="btn primary" disabled={!!busy} onClick={()=>cycleAction("ACTIVATE")}>{busy==="ACTIVATE"?"جارٍ التفعيل...":"تفعيل البرنامج للمعلمين"}</button>:c.status==="ACTIVE"?<button className="btn danger" disabled={!!busy} onClick={()=>cycleAction("CLOSE")}>{busy==="CLOSE"?"جارٍ الإغلاق...":"إغلاق الدورة"}</button>:null}</section>}

    {c&&(data.can_activate||data.can_manage)&&c.status!=="SCHEDULED"&&<section className="panel behavioral-participation-report"><div className="panel-title"><div><h3>تقرير متابعة ترشيحات المعلمين</h3><p>يعرض من أكمل ترشيح 3 طلاب في كل فصل مسند له، ومن لم يبدأ أو لم يكمل بعد.</p></div><div className="behavioral-report-actions no-print"><button className="mini-btn" onClick={()=>load()}>تحديث التقرير</button><button className="mini-btn" onClick={printParticipation}>طباعة التقرير</button></div></div><div className="behavioral-report-stats"><article><span>إجمالي المعلمين</span><strong>{participationStats.total}</strong></article><article className="complete"><span>أكملوا الترشيح</span><strong>{participationStats.complete}</strong></article><article className="partial"><span>ترشيح جزئي</span><strong>{participationStats.partial}</strong></article><article className="missing"><span>لم يرشحوا</span><strong>{participationStats.missing}</strong></article><article className="account"><span>بدون حساب مفعل</span><strong>{participationStats.noAccount}</strong></article></div><div className="behavioral-report-filters no-print"><button className={reportFilter==="ALL"?"active":""} onClick={()=>setReportFilter("ALL")}>الكل</button><button className={reportFilter==="NOT_NOMINATED"?"active":""} onClick={()=>setReportFilter("NOT_NOMINATED")}>لم يرشح</button><button className={reportFilter==="PARTIAL"?"active":""} onClick={()=>setReportFilter("PARTIAL")}>جزئي</button><button className={reportFilter==="COMPLETE"?"active":""} onClick={()=>setReportFilter("COMPLETE")}>مكتمل</button><button className={reportFilter==="NO_ACCOUNT"?"active":""} onClick={()=>setReportFilter("NO_ACCOUNT")}>بدون حساب</button></div>{filteredParticipation.length?<div className="table-wrap behavioral-report-table"><table><thead><tr><th>المعلم</th><th>الحالة</th><th>الفصول</th><th>المكتمل</th><th>المتبقي</th><th>الطلاب المرشحون</th></tr></thead><tbody>{filteredParticipation.map(t=><tr key={t.staff_id} className={`participation-${t.status.toLowerCase()}`}><td><b>{t.teacher_name}</b><small>{t.subject_name||"—"}</small></td><td><span className={`participation-status ${t.status.toLowerCase()}`}>{participationLabel(t.status)}</span></td><td><b>{t.assigned_classes}</b>{t.classes?.length>0&&<div className="participation-classes">{t.classes.map(x=><span key={x.class_id} className={x.complete?"done":"pending"}>{x.grade_name} / {x.class_name}: {x.nomination_count}/3</span>)}</div>}</td><td><strong>{t.completed_classes}</strong></td><td><strong>{t.remaining_classes}</strong></td><td><strong>{t.nomination_count}</strong></td></tr>)}</tbody></table></div>:<div className="empty">لا توجد نتائج مطابقة لهذا الفلتر.</div>}</section>}

    {c&&data.is_teacher&&data.visible_to_teacher&&<section className="behavioral-nomination-area"><div className="section-intro"><div><h3>ترشيحاتك</h3><p>اختر 3 طلاب من كل فصل مسند لك. يمكنك تعديل الاختيارات وإعادة حفظها ما دامت الدورة مفتوحة.</p></div></div>{classGroups.length?<div className="behavioral-class-grid">{classGroups.map(group=>{const choices=selected[group.id]||[];return <article className="panel behavioral-class-card" key={group.id}><div className="behavioral-class-head"><div><span>{group.grade}</span><h4>فصل {group.name}</h4></div><b className={choices.length===3?"complete":""}>{choices.length}/3</b></div><div className="behavioral-student-picker">{group.students.map(s=><button type="button" key={s.id} className={choices.includes(s.id)?"selected":""} onClick={()=>toggle(group.id,s.id)}><span className="student-choice-mark">{choices.includes(s.id)?"✓":""}</span><div><b>{s.name}</b><small>{s.student_no}</small></div></button>)}</div><button className="btn primary full" disabled={busy===group.id||choices.length!==3} onClick={()=>saveClass(group.id)}>{busy===group.id?"جارٍ الحفظ...":"حفظ 3 ترشيحات"}</button></article>})}</div>:<div className="panel empty">لا توجد فصول مسندة لحسابك.</div>}</section>}

    {c&&data.is_teacher&&!data.visible_to_teacher&&c.status!=="CLOSED"&&!data.can_activate&&<section className="panel empty">البرنامج غير متاح للترشيح الآن. لن يظهر للمعلمين إلا بعد تفعيل الموجه وبدء المدة المحددة.</section>}

    {c&&<section className="panel behavioral-leaderboard"><div className="panel-title"><div><h3>{c.status==="CLOSED"?"النتيجة النهائية":"صدارة التميز السلوكي"}</h3><p>الترتيب حسب إجمالي عدد ترشيحات المعلمين. عند التعادل يشترك الطلاب في نفس المركز، وبعد الإغلاق يفوز صاحب/أصحاب المركز الأول.</p></div><span className="counter">{data.leaderboard?.length||0}</span></div>{data.leaderboard?.length?<div className="behavioral-ranking-list">{data.leaderboard.map(x=><article key={x.student_id} className={x.rank<=3?`top rank-${x.rank}`:""}><span className="behavioral-rank">{x.rank}</span><div><b>{x.student_name}</b><small>{x.grade_name} — فصل {x.class_name} · {x.student_no}</small></div><strong>{x.nomination_count}<small> ترشيح</small></strong>{c.status==="CLOSED"&&x.rank===1&&<em>فائز</em>}</article>)}</div>:<div className="empty">لم تسجل ترشيحات في هذه الدورة حتى الآن.</div>}</section>}
    {msg&&<div className="notice sticky-note">{msg}</div>}
  </main></>;
}
