import { useEffect, useMemo, useState } from "react";
import { niceError, rpc } from "./client";
import "./engagement.css";

type Student={id:string;student_no:string;name:string;grade_name:string;class_name:string;class_id?:string;points:number};
type Cycle={id:string;title_ar:string;description_ar:string;starts_at:string;ends_at:string;status:"SCHEDULED"|"ACTIVE"|"CLOSED";activated_at?:string|null;closed_at?:string|null};
type Nomination={class_id:string;student_ids:string[]};
type Leader={student_id:string;student_name:string;student_no:string;grade_name:string;class_name:string;nomination_count:number;rank:number};
type Data={is_teacher:boolean;can_activate:boolean;can_manage:boolean;visible_to_teacher:boolean;cycle:Cycle|null;cycles:Cycle[];assigned_class_ids:string[];my_nominations:Nomination[];leaderboard:Leader[]};
type Props={students:Student[]};
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString("ar-SA",{year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):"—";
const statusLabel=(s?:string)=>s==="ACTIVE"?"مفعلة":s==="SCHEDULED"?"بانتظار تفعيل الموجه":s==="CLOSED"?"منتهية":"غير مجدولة";

export default function BehavioralExcellence({students}:Props){
  const[data,setData]=useState<Data|null>(null);const[selected,setSelected]=useState<Record<string,string[]>>({});const[busy,setBusy]=useState("");const[msg,setMsg]=useState("");
  async function load(){try{const d=await rpc<Data>("api_behavioral_excellence");setData(d);const initial:Record<string,string[]>={};for(const n of d.my_nominations||[])initial[n.class_id]=(n.student_ids||[]).map(String);setSelected(initial)}catch(e){setMsg(niceError(e))}}
  useEffect(()=>{load()},[]);
  const classGroups=useMemo(()=>{if(!data)return[];const allowed=new Set((data.assigned_class_ids||[]).map(String));const map=new Map<string,{id:string;grade:string;name:string;students:Student[]}>();for(const s of students){if(!s.class_id||!allowed.has(String(s.class_id)))continue;const key=String(s.class_id);if(!map.has(key))map.set(key,{id:key,grade:s.grade_name,name:s.class_name,students:[]});map.get(key)!.students.push(s)}return [...map.values()].sort((a,b)=>`${a.grade}${a.name}`.localeCompare(`${b.grade}${b.name}`,"ar"))},[students,data]);
  function toggle(classId:string,studentId:string){setMsg("");setSelected(v=>{const current=v[classId]||[];if(current.includes(studentId))return{...v,[classId]:current.filter(x=>x!==studentId)};if(current.length>=3){setMsg("لكل فصل 3 ترشيحات فقط. ألغِ اختيار طالب أولًا لتختار غيره.");return v}return{...v,[classId]:[...current,studentId]}})}
  async function saveClass(classId:string){const ids=selected[classId]||[];if(ids.length!==3){setMsg("اختر 3 طلاب بالضبط من هذا الفصل قبل الحفظ.");return}if(!data?.cycle)return;setBusy(classId);setMsg("");try{await rpc("api_behavioral_nominate",{p_cycle_id:data.cycle.id,p_class_id:classId,p_student_ids:ids});setMsg("تم حفظ ترشيحات التميز السلوكي لهذا الفصل.");await load()}catch(e){setMsg(niceError(e))}finally{setBusy("")}}
  async function cycleAction(action:"ACTIVATE"|"CLOSE"){if(!data?.cycle)return;setBusy(action);setMsg("");try{await rpc("api_behavioral_set_cycle_state",{p_cycle_id:data.cycle.id,p_action:action});setMsg(action==="ACTIVATE"?"تم تفعيل البرنامج. سيظهر للمعلمين داخل المدة المحددة.":"تم إغلاق الدورة وإيقاف الترشيحات.");await load();window.dispatchEvent(new Event("behavioral-status-changed"))}catch(e){setMsg(niceError(e))}finally{setBusy("")}}
  if(!data)return <><header className="topbar"><div><h1>التميز السلوكي</h1><p>جارٍ تحميل البرنامج...</p></div></header><main className="content"><div className="panel empty">جارٍ التحميل...</div></main></>;
  const c=data.cycle;
  return <><header className="topbar"><div><h1>التميز السلوكي</h1><p>برنامج دوري لترشيح الطلاب الأكثر تميزًا في السلوك</p></div>{c&&<span className={`behavioral-header-status ${c.status.toLowerCase()}`}>{statusLabel(c.status)}</span>}</header><main className="content behavioral-page">
    {c?<section className="panel behavioral-hero"><div><span className="eyebrow">برنامج دوري</span><h2>{c.title_ar}</h2><p>{c.description_ar}</p><div className="behavioral-dates"><span><small>البداية</small><b>{fmt(c.starts_at)}</b></span><span><small>النهاية</small><b>{fmt(c.ends_at)}</b></span></div></div><div className="behavioral-rule"><strong>3</strong><span>طلاب من كل فصل<br/>لكل معلم</span></div></section>:<section className="panel empty">لم يجهز مدير النظام دورة للتميز السلوكي حتى الآن.</section>}

    {c&&data.can_activate&&<section className="panel guidance-activation"><div><h3>تحكم الموجه الطلابي</h3><p>{c.status==="SCHEDULED"?"الدورة مجهزة ولكنها مخفية عن المعلمين. فعّلها عندما تريد بدء البرنامج.":c.status==="ACTIVE"?"الدورة مفعلة. يستطيع المعلمون الترشيح أثناء المدة المحددة.":"هذه الدورة منتهية."}</p></div>{c.status==="SCHEDULED"?<button className="btn primary" disabled={!!busy} onClick={()=>cycleAction("ACTIVATE")}>{busy==="ACTIVATE"?"جارٍ التفعيل...":"تفعيل البرنامج للمعلمين"}</button>:c.status==="ACTIVE"?<button className="btn danger" disabled={!!busy} onClick={()=>cycleAction("CLOSE")}>{busy==="CLOSE"?"جارٍ الإغلاق...":"إغلاق الدورة"}</button>:null}</section>}

    {c&&data.is_teacher&&data.visible_to_teacher&&<section className="behavioral-nomination-area"><div className="section-intro"><div><h3>ترشيحاتك</h3><p>اختر 3 طلاب من كل فصل مسند لك. يمكنك تعديل الاختيارات وإعادة حفظها ما دامت الدورة مفتوحة.</p></div></div>{classGroups.length?<div className="behavioral-class-grid">{classGroups.map(group=>{const choices=selected[group.id]||[];return <article className="panel behavioral-class-card" key={group.id}><div className="behavioral-class-head"><div><span>{group.grade}</span><h4>فصل {group.name}</h4></div><b className={choices.length===3?"complete":""}>{choices.length}/3</b></div><div className="behavioral-student-picker">{group.students.map(s=><button type="button" key={s.id} className={choices.includes(s.id)?"selected":""} onClick={()=>toggle(group.id,s.id)}><span className="student-choice-mark">{choices.includes(s.id)?"✓":""}</span><div><b>{s.name}</b><small>{s.student_no}</small></div></button>)}</div><button className="btn primary full" disabled={busy===group.id||choices.length!==3} onClick={()=>saveClass(group.id)}>{busy===group.id?"جارٍ الحفظ...":"حفظ 3 ترشيحات"}</button></article>})}</div>:<div className="panel empty">لا توجد فصول مسندة لحسابك.</div>}</section>}

    {c&&data.is_teacher&&!data.visible_to_teacher&&c.status!=="CLOSED"&&!data.can_activate&&<section className="panel empty">البرنامج غير متاح للترشيح الآن. لن يظهر للمعلمين إلا بعد تفعيل الموجه وبدء المدة المحددة.</section>}

    {c&&<section className="panel behavioral-leaderboard"><div className="panel-title"><div><h3>{c.status==="CLOSED"?"النتيجة النهائية":"صدارة التميز السلوكي"}</h3><p>الترتيب حسب إجمالي عدد ترشيحات المعلمين. عند التعادل يشترك الطلاب في نفس المركز.</p></div><span className="counter">{data.leaderboard?.length||0}</span></div>{data.leaderboard?.length?<div className="behavioral-ranking-list">{data.leaderboard.map(x=><article key={x.student_id} className={x.rank<=3?`top rank-${x.rank}`:""}><span className="behavioral-rank">{x.rank}</span><div><b>{x.student_name}</b><small>{x.grade_name} — فصل {x.class_name} · {x.student_no}</small></div><strong>{x.nomination_count}<small> ترشيح</small></strong>{c.status==="CLOSED"&&x.rank<=3&&<em>فائز</em>}</article>)}</div>:<div className="empty">لم تسجل ترشيحات في هذه الدورة حتى الآن.</div>}</section>}
    {msg&&<div className="notice sticky-note">{msg}</div>}
  </main></>;
}
