import { useEffect, useState } from "react";
import { niceError, rpc } from "./client";
import "./engagement.css";
import "./report-print.css";

type Comp={id:string;title_ar:string;body_ar:string;starts_at:string;ends_at?:string|null;is_published:boolean;announcement_type?:string;participant_count?:number;target_classes?:Array<{id:string;grade_name:string;class_name:string}>};
type Participant={student_id:string;student_no:string;student_name:string;grade_name:string;class_name:string;joined_at:string};
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString("ar-SA",{year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):"—";
const esc=(v:any)=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]||m));

export default function CompetitionManagementPanel(){
  const[items,setItems]=useState<Comp[]>([]);const[open,setOpen]=useState("");const[people,setPeople]=useState<Record<string,Participant[]>>({});const[busy,setBusy]=useState("");const[msg,setMsg]=useState("");
  async function load(){try{const rows=await rpc<Comp[]>("api_admin_announcements");setItems((rows||[]).filter(x=>x.announcement_type==="TARGETED_COMPETITION"))}catch(e){setMsg(niceError(e))}}
  useEffect(()=>{load()},[]);
  async function getPeople(id:string){if(people[id])return people[id];const list=await rpc<Participant[]>("api_admin_competition_participants",{p_competition_id:id});const ready=list||[];setPeople(v=>({...v,[id]:ready}));return ready}
  async function showPeople(id:string){if(open===id){setOpen("");return}setOpen(id);try{await getPeople(id)}catch(e){setMsg(niceError(e))}}
  async function printPeople(c:Comp){
    const w=window.open("","_blank","width=1200,height=850");
    if(!w){window.alert("تعذر فتح نافذة التقرير. اسمح بالنوافذ المنبثقة لهذا الموقع ثم أعد المحاولة.");return}
    w.document.open();
    w.document.write('<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>جارٍ تجهيز التقرير</title><style>body{font-family:Tahoma,Arial,sans-serif;display:grid;place-items:center;min-height:80vh;color:#335;padding:30px}.loading{font-size:18px;font-weight:700}</style></head><body><div class="loading">جارٍ تحميل أسماء المنضمين وتجهيز التقرير...</div></body></html>');
    w.document.close();
    setBusy(c.id+"PRINT");setMsg("");
    try{
      const list=await getPeople(c.id);
      if(!list.length){w.document.open();w.document.write('<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>قائمة المنضمين</title></head><body style="font-family:Tahoma,Arial,sans-serif;padding:30px"><h2>لا يوجد طلاب منضمون لهذه المسابقة حتى الآن.</h2><button onclick="window.close()">إغلاق</button></body></html>');w.document.close();return}
      const targets=c.target_classes?.map(x=>`${x.grade_name} / ${x.class_name}`).join("، ")||"جميع الفصول المستهدفة";
      const rows=list.map((p,index)=>`<tr><td>${index+1}</td><td><b>${esc(p.student_name)}</b></td><td>${esc(p.grade_name)} / ${esc(p.class_name)}</td><td>${esc(p.student_no)}</td><td>${esc(fmt(p.joined_at))}</td></tr>`).join("");
      const schoolLogo=new URL(`${import.meta.env.BASE_URL}school-logo.png`,window.location.origin).href;
      const guidanceLogo=new URL(`${import.meta.env.BASE_URL}guidance-logo.png`,window.location.origin).href;
      const printedAt=new Date().toLocaleString("ar-SA",{year:"numeric",month:"long",day:"numeric",hour:"numeric",minute:"2-digit"});
      w.document.open();
      w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>قائمة المنضمين — ${esc(c.title_ar)}</title><style>
@page{size:A4 landscape;margin:11mm}*{box-sizing:border-box}html,body{background:#fff;color:#17242c}body{margin:0;padding:22px;font-family:Tahoma,Arial,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}.report{width:100%;display:block}.head{display:grid;grid-template-columns:100px 1fr 100px;align-items:center;gap:12px;border-bottom:3px solid #0b7562;padding-bottom:12px;margin-bottom:14px}.head img{width:70px;height:70px;object-fit:contain;justify-self:center}.head .center{text-align:center}.head h1{margin:3px 0;font-size:22px;color:#153f62}.head h2{margin:0;font-size:12px;color:#0b7562}.head p{margin:5px 0 0;font-size:10px;color:#667983}.meta{display:flex;justify-content:space-between;gap:10px;padding:8px 10px;margin-bottom:12px;background:#f4f8f8;border:1px solid #dbe6e8;border-radius:8px;font-size:10px}.meta b{color:#0b7562}table{display:table!important;width:100%!important;border-collapse:collapse!important;table-layout:auto!important;font-size:11px!important;background:#fff!important;visibility:visible!important;opacity:1!important}thead{display:table-header-group!important}tbody{display:table-row-group!important}tr{display:table-row!important;break-inside:avoid;page-break-inside:avoid}th,td{display:table-cell!important;border:1px solid #c7d4d8!important;padding:8px!important;text-align:right!important;vertical-align:middle!important;color:#17242c!important;visibility:visible!important;opacity:1!important}th{background:#eaf3f1!important;color:#124d45!important;font-weight:800!important}tbody tr:nth-child(even) td{background:#f9fbfb!important}.footer{margin-top:12px;padding-top:8px;border-top:1px solid #d5e0e3;display:flex;justify-content:space-between;font-size:9px;color:#748690}.tools{display:flex;justify-content:center;gap:8px;margin:18px 0}.tools button{border:0;border-radius:10px;padding:10px 22px;font-weight:800;cursor:pointer;font-family:inherit}.print{background:#0b7562;color:#fff}.close{background:#eef3f4;color:#31434c}@media print{body{padding:0}.tools{display:none!important}.report{display:block!important;visibility:visible!important}table{display:table!important;visibility:visible!important}}
</style></head><body><main class="report"><header class="head"><img src="${esc(schoolLogo)}" alt="شعار المدرسة"><div class="center"><h2>مدارس المشكاة الأهلية — بنك التميز الطلابي</h2><h1>قائمة المنضمين — ${esc(c.title_ar)}</h1><p>الفترة: ${esc(fmt(c.starts_at))} — ${esc(fmt(c.ends_at))}<br>الفصول المستهدفة: ${esc(targets)}</p></div><img src="${esc(guidanceLogo)}" alt="شعار التوجيه الطلابي"></header><div class="meta"><span>عدد الطلاب المنضمين: <b>${list.length.toLocaleString("ar-SA")}</b></span><span>تاريخ إعداد التقرير: <b>${esc(printedAt)}</b></span></div><table id="participants-report"><thead><tr><th style="width:6%">م</th><th>اسم الطالب</th><th>الصف / الفصل</th><th>رقم الطالب</th><th>وقت الانضمام</th></tr></thead><tbody>${rows}</tbody></table><footer class="footer"><span>التوجيه الطلابي</span><span>تم إنشاء التقرير إلكترونيًا من نظام بنك التميز الطلابي</span></footer><div class="tools"><button class="print" onclick="window.print()">طباعة / حفظ PDF</button><button class="close" onclick="window.close()">إغلاق</button></div></main></body></html>`);
      w.document.close();
      w.focus();
    }catch(e){
      const text=niceError(e);setMsg(text);
      w.document.open();w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>تعذر تجهيز التقرير</title></head><body style="font-family:Tahoma,Arial,sans-serif;padding:30px"><h2>تعذر تجهيز التقرير</h2><p>${esc(text)}</p><button onclick="window.close()">إغلاق</button></body></html>`);w.document.close();
    }finally{setBusy("")}
  }
  async function action(id:string,kind:"STOP"|"RESUME"|"DELETE"){if(kind==="DELETE"&&!window.confirm("حذف المسابقة من النظام؟ ستختفي من الطلاب ومن قائمة المسابقات، مع الاحتفاظ بسجل داخلي للتدقيق."))return;setBusy(id+kind);setMsg("");try{await rpc("api_admin_manage_competition",{p_competition_id:id,p_action:kind});setMsg(kind==="STOP"?"تم إيقاف المسابقة ولن تظهر للطلاب.":kind==="RESUME"?"تم إعادة تفعيل المسابقة.":"تم حذف المسابقة من القوائم.");setOpen("");await load()}catch(e){setMsg(niceError(e))}finally{setBusy("")}}
  return <section className="panel competition-management"><div className="panel-title"><div><h3>إدارة المسابقات المنشورة</h3><p>إيقاف أو إعادة تشغيل أو حذف المسابقة، ومتابعة الطلاب الذين ضغطوا «انضمام».</p></div><span className="counter">{items.length}</span></div>{items.length?<div className="competition-admin-list">{items.map(c=><article key={c.id}><div className="competition-admin-head"><div><span className={c.is_published?"status-live":"status-stopped"}>{c.is_published?"منشورة":"موقوفة"}</span><h4>{c.title_ar}</h4><p>{c.body_ar}</p><small>{fmt(c.starts_at)} — {fmt(c.ends_at)} · {c.target_classes?.map(x=>`${x.grade_name} / ${x.class_name}`).join("، ")||"—"}</small></div><div className="competition-admin-actions"><button className="mini-btn" onClick={()=>showPeople(c.id)}>المنضمون ({c.participant_count||0})</button>{c.is_published?<button className="mini-btn warning" disabled={busy.startsWith(c.id)} onClick={()=>action(c.id,"STOP")}>إيقاف</button>:<button className="mini-btn" disabled={busy.startsWith(c.id)} onClick={()=>action(c.id,"RESUME")}>إعادة تشغيل</button>}<button className="mini-btn danger" disabled={busy.startsWith(c.id)} onClick={()=>action(c.id,"DELETE")}>حذف</button></div></div>{open===c.id&&<div className="competition-participants"><div className="participant-title"><div><b>الطلاب المنضمون</b><span>{people[c.id]?.length||0} طالب</span></div>{(people[c.id]?.length||0)>0&&<button className="report-print-btn no-print" disabled={busy===c.id+"PRINT"} onClick={()=>printPeople(c)}>{busy===c.id+"PRINT"?"جارٍ تجهيز التقرير...":"طباعة / حفظ PDF"}</button>}</div>{people[c.id]?.length?<div className="compact-table no-auto-report-print"><table><thead><tr><th>الطالب</th><th>الصف / الفصل</th><th>رقم الطالب</th><th>وقت الانضمام</th></tr></thead><tbody>{people[c.id].map(p=><tr key={p.student_id}><td>{p.student_name}</td><td>{p.grade_name} / {p.class_name}</td><td>{p.student_no}</td><td>{fmt(p.joined_at)}</td></tr>)}</tbody></table></div>:<div className="empty">لا يوجد طلاب منضمون حتى الآن.</div>}</div>}</article>)}</div>:<div className="empty">لا توجد مسابقات موجهة تم إطلاقها حتى الآن.</div>}{msg&&<div className="notice compact-notice">{msg}</div>}</section>;
}
