import { FormEvent, useEffect, useState } from "react";
import { niceError, rpc } from "./client";
import "./feature-upgrade.css";

type Rule = { id:string; name_ar:string; description_ar?:string|null; points:number; is_mega:boolean; is_active:boolean };
type Announcement = { id:string; title_ar:string; body_ar:string; starts_at:string; ends_at?:string|null; is_published:boolean; created_at:string };
type Board = { available:boolean; name_ar?:string; week_no?:number; starts_on?:string; ends_on?:string; status?:string; reward?:string; criteria?:Array<{key:string;label:string;weight:number;max_score:number}>; weeks?:Array<{id:string;week_no:number;name_ar:string;starts_on:string;ends_on:string;status:string}> };

export default function SystemControlPanel(){
  const[rules,setRules]=useState<Rule[]>([]);const[draft,setDraft]=useState<Record<string,string>>({});const[ann,setAnn]=useState<Announcement[]>([]);const[board,setBoard]=useState<Board|null>(null);const[busy,setBusy]=useState("");const[msg,setMsg]=useState("");
  const[title,setTitle]=useState("");const[body,setBody]=useState("");const[endDate,setEndDate]=useState("");
  async function load(){try{const[r,a,b]=await Promise.all([rpc<Rule[]>("api_admin_point_rules"),rpc<Announcement[]>("api_admin_announcements"),rpc<Board>("api_khameesna_competition_board")]);setRules(r);setAnn(a);setBoard(b);setDraft(Object.fromEntries(r.map(x=>[x.id,String(x.points)])))}catch(e){setMsg(niceError(e))}}
  useEffect(()=>{load()},[]);
  async function saveRule(r:Rule){const p=Number(draft[r.id]);if(!Number.isFinite(p)||p<1||p>100){setMsg("قيمة النقاط يجب أن تكون من 1 إلى 100.");return}setBusy(r.id);setMsg("");try{await rpc("api_admin_set_point_rule",{p_rule_id:r.id,p_points:p});setMsg(`تم تثبيت قيمة «${r.name_ar}» على ${p} نقطة. المعلم لن يستطيع تغييرها.`);await load()}catch(e){setMsg(niceError(e))}finally{setBusy("")}}
  async function publish(e:FormEvent){e.preventDefault();setBusy("announcement");setMsg("");try{await rpc("api_admin_publish_announcement",{p_title_ar:title,p_body_ar:body,p_ends_at:endDate?new Date(endDate+"T23:59:59+03:00").toISOString():null});setTitle("");setBody("");setEndDate("");setMsg("تم نشر إعلان المسابقة في بوابة الطلاب.");await load()}catch(e){setMsg(niceError(e))}finally{setBusy("")}}
  const d=(v?:string)=>v?new Date(v+(/T/.test(v)?"":"T12:00:00")).toLocaleDateString("ar-SA",{day:"numeric",month:"short"}):"—";
  return <><header className="topbar"><div><h1>إعدادات مدير النظام</h1><p>قيم البطاقات وإعلانات المسابقات — هذه الصفحة متاحة لمدير النظام فقط</p></div></header><main className="content system-control">
    <section className="panel"><div className="panel-title"><div><h3>قيم بطاقات التميز</h3><p>المعلم يختار البطاقة فقط. عدد النقاط هنا هو القيمة النهائية التي تعتمدها قاعدة البيانات.</p></div><span className="counter">{rules.length}</span></div><div className="point-rule-admin">{rules.map(r=><article key={r.id} className={r.is_mega?"mega-rule-admin":""}><div><b>{r.name_ar}</b><small>{r.is_mega?"شيك عملاق — للإدارة والتوجيه فقط":r.description_ar||"بطاقة تميز"}</small></div><label><input type="number" min="1" max="100" value={draft[r.id]??r.points} onChange={e=>setDraft(v=>({...v,[r.id]:e.target.value}))}/><span>نقطة</span></label><button className="btn primary" disabled={busy===r.id} onClick={()=>saveRule(r)}>{busy===r.id?"جارٍ الحفظ...":"حفظ القيمة"}</button></article>)}</div></section>

    <section className="panel"><div className="panel-title"><div><h3>إصدار «خميسنا غير»</h3><p>سلسلة أسبوعية من الأسبوع الخامس إلى الأسبوع السابع عشر.</p></div><span className="counter">13 أسبوعًا</span></div>{board?.available&&<><div className="kh-system-summary"><div><small>الأسبوع الأقرب</small><b>{board.name_ar}</b><span>{d(board.starts_on)} — {d(board.ends_on)}</span></div><div><small>الجائزة</small><b>{board.reward}</b></div></div><div className="criteria-admin">{board.criteria?.map(c=><div key={c.key}><b>{c.label}</b><span>{c.weight}% · من {c.max_score} درجات</span></div>)}</div><div className="weeks-admin">{board.weeks?.map(w=><span key={w.id} className={w.status.toLowerCase()}>الأسبوع {w.week_no}</span>)}</div></>}</section>

    <section className="panel"><div className="panel-title"><div><h3>إعلانات المسابقات للطلاب</h3><p>أي إعلان تنشره هنا يظهر مباشرة داخل حسابات الطلاب.</p></div></div><form className="announcement-form" onSubmit={publish}><label>عنوان الإعلان<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="مثال: مسابقة الطالب المثالي"/></label><label>نص الإعلان<textarea required rows={4} value={body} onChange={e=>setBody(e.target.value)} placeholder="تفاصيل المسابقة والموعد والجائزة..."/></label><label>نهاية عرض الإعلان — اختياري<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><button className="btn primary" disabled={busy==="announcement"}>{busy==="announcement"?"جارٍ النشر...":"نشر الإعلان للطلاب"}</button></form><div className="admin-announcements">{ann.map(a=><article key={a.id}><div><b>{a.title_ar}</b><p>{a.body_ar}</p></div><span>{a.is_published?"منشور":"غير منشور"}</span></article>)}</div></section>
    {msg&&<div className="notice sticky-note">{msg}</div>}
  </main></>;
}
